# Generated by Django 4.2.3 on 2023-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_code',
            field=models.CharField(default='XEYaLU', max_length=6),
        ),
    ]
