# Generated by Django 4.2.3 on 2023-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='guest',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(default='/static/img/guest.webp', upload_to='images/'),
        ),
    ]
